const users = [
  {
    id: 1,
    name: 'Prewitt Lemaitre',
    type: 'internal',
    alerts: [
      'success',
      'success',
      'warning',
      'success',
      'warning',
      'danger',
      'success',
      'warning',
      'danger',
      'success',
      'danger',
      'success',
      'danger',
      'danger',
      'danger',
      'success',
      'warning',
      'warning',
      'warning',
      'success',
      'danger',
      'danger',
      'warning',
      'warning',
      'success',
      'danger',

    ]
    
  },
  {
    id: 2,
    name: 'Prewitt Lemaitre',
    type: 'external',
    alerts: [
      'success',
      'success',
      'warning',
      'success',
      'warning',
      'danger',
      'success',
      'warning',
      'danger',
      'success',
      'danger',
      'success',
      'danger',
      'danger',
      'danger',
      'success',
      'warning',
      'warning',
      'warning',
      'success',
      'danger',
      'danger',
      'warning',
      'warning',
      'success',
      'danger',

    ]
    
  },
  {
    id: 3,
    name: 'Prewitt Lemaitre',
    type: 'external',
    alerts: [
      'success',
      'success',
      'warning',
      'success',
      'warning',
      'danger',
      'success',
      'warning',
      'danger',
      'success',
      'danger',
      'success',
      'danger',
      'danger',
      'danger',
      'success',
      'warning',
      'warning',
      'warning',
      'success',
      'danger',
      'danger',
      'warning',
      'warning',
      'success',
      'danger',

    ]
    
  },
  {
    id: 4,
    name: 'Prewitt Lemaitre',
    type: 'internal',
    alerts: [
      'success',
      'success',
      'warning',
      'success',
      'warning',
      'danger',
      'success',
      'warning',
      'danger',
      'success',
      'danger',
      'success',
      'danger',
      'danger',
      'danger',
      'success',
      'warning',
      'warning',
      'warning',
      'success',
      'danger',
      'danger',
      'warning',
      'warning',
      'success',
      'danger',

    ]
    
  },
  {
    id: 5,
    name: 'Prewitt Lemaitre',
    type: 'external',
    alerts: [
      'success',
      'success',
      'warning',
      'success',
      'warning',
      'danger',
      'success',
      'warning',
      'danger',
      'success',
      'danger',
      'success',
      'danger',
      'danger',
      'danger',
      'success',
      'warning',
      'warning',
      'warning',
      'success',
      'danger',
      'danger',
      'warning',
      'warning',
      'success',
      'danger',

    ]
    
  },
  {
    id: 6,
    name: 'Prewitt Lemaitre',
    type: 'internal',
    alerts: [
      'success',
      'success',
      'warning',
      'success',
      'warning',
      'danger',
      'success',
      'warning',
      'danger',
      'success',
      'danger',
      'success',
      'danger',
      'danger',
      'danger',
      'success',
      'warning',
      'warning',
      'warning',
      'success',
      'danger',
      'danger',
      'warning',
      'warning',
      'success',
      'danger',

    ]
    
  },
  {
    id: 7,
    name: 'Prewitt Lemaitre',
    type: 'external',
    alerts: [
      'success',
      'success',
      'warning',
      'success',
      'warning',
      'danger',
      'success',
      'warning',
      'danger',
      'success',
      'danger',
      'success',
      'danger',
      'danger',
      'danger',
      'success',
      'warning',
      'warning',
      'warning',
      'success',
      'danger',
      'danger',
      'warning',
      'warning',
      'success',
      'danger',

    ]
    
  },
  {
    id: 8,
    name: 'Prewitt Lemaitre',
    type: 'internal',
    alerts: [
      'success',
      'success',
      'warning',
      'success',
      'warning',
      'danger',
      'success',
      'warning',
      'danger',
      'success',
      'danger',
      'success',
      'danger',
      'danger',
      'danger',
      'success',
      'warning',
      'warning',
      'warning',
      'success',
      'danger',
      'danger',
      'warning',
      'warning',
      'success',
      'danger',

    ]
    
  },
  {
    id: 9,
    name: 'Prewitt Lemaitre',
    type: 'internal',
    alerts: [
      'success',
      'success',
      'warning',
      'success',
      'warning',
      'danger',
      'success',
      'warning',
      'danger',
      'success',
      'danger',
      'success',
      'danger',
      'danger',
      'danger',
      'success',
      'warning',
      'warning',
      'warning',
      'success',
      'danger',
      'danger',
      'warning',
      'warning',
      'success',
      'danger',

    ]
    
  },
  {
    id: 10,
    name: 'Prewitt Lemaitre',
    type: 'external',
    alerts: [
      'success',
      'success',
      'warning',
      'success',
      'warning',
      'danger',
      'success',
      'warning',
      'danger',
      'success',
      'danger',
      'success',
      'danger',
      'danger',
      'danger',
      'success',
      'warning',
      'warning',
      'warning',
      'success',
      'danger',
      'danger',
      'warning',
      'warning',
      'success',
      'danger',

    ]
    
  },

];




function createCell(label, upperValue, lowerValue) {
	return { label, upperValue, lowerValue };
}

const columns = [
	createCell('Visite médicale', 12, 106),
	createCell('Poste de sécurité', 90, 12),
	createCell('Secouriste industriel', 34, 390),
	createCell('Eq. Première Intervention', 32, 98),
	createCell('Base', 23, 89),
	createCell('Cadre', 32, 78),
	createCell('Nacelle', 109, 79),
	createCell('Harnais', 102, 89),
	createCell('Travaux en hauteur', 19, 56),
	createCell('Utilisateur', 12, 23),
	createCell('Monteur', 90, 87),
	createCell('Inspecteur', 56, 65),
	createCell('Pontier cabine', 89, 24),
	createCell('Pontier poiré', 34, 90),
	createCell('Radiocommandé', 23, 43),
	createCell('Elévateur à fourches', 12, 90),
	createCell('Télescopique rotatif', 87, 34),
	createCell('G. de charges (RIGGER)', 87, 34),
	createCell('Elingage de charges', 23, 89),
	createCell('Elingage de charges', 34, 76),
	createCell('Elingage de charges', 34, 76),
	createCell('Elingage de charges', 34, 76),
	createCell('Elingage de charges', 34, 76),
	createCell('Elingage de charges', 34, 76),
	createCell('Elingage de charges', 34, 76),
	createCell('Elingage de charges', 34, 76),
];


export { columns, users };